import { formatGBP, formatPercent } from "../../src/lib/format";
import type { CheckResult, Mismatch } from "./types";

// GOV.UK source links, shared by both PR bodies so a maintainer can always
// cross-check — including when an auto PR falls back to a manual merge.
const SOURCE_LINKS = [
  "### Cross-check against the source",
  "- [Thresholds and repayment rates (GOV.UK)](https://www.gov.uk/repaying-your-student-loan/what-you-pay)",
  "- [Write-off periods (GOV.UK)](https://www.gov.uk/repaying-your-student-loan/when-your-student-loan-gets-written-off-or-cancelled)",
].join("\n");

/** Human-readable value for a mismatch field (a rate as %, a threshold as £). */
export function formatFieldValue(field: string, value: number): string {
  if (field.endsWith(".repaymentRate")) {
    // 1-decimal precision avoids float noise (0.09 → "9%") without collapsing a
    // sub-point change to identical from/to values in the review body.
    return formatPercent(Math.round(value * 1000) / 10);
  }
  if (field.endsWith(".writeOffYears")) {
    return `${String(value)} years`;
  }
  if (field.startsWith("CURRENT_RATES.")) {
    return formatPercent(value);
  }
  // Repayment and interest thresholds are pound amounts.
  return formatGBP(value);
}

/** Render the PR description for a figure change (auto-merge or review). */
export function renderPrBody(
  status: CheckResult["status"],
  mismatches: Mismatch[],
  reviewReasons: string[] | undefined,
): string {
  const changes =
    mismatches.length > 0
      ? mismatches
          .map(
            (m) =>
              `- ${m.field}: ${formatFieldValue(m.field, m.current)} → ${formatFieldValue(m.field, m.scraped)}`,
          )
          .join("\n")
      : "- (generated content changed; no figure value moved)";

  if (status === "mismatch-auto") {
    return [
      "## Summary",
      "",
      "The daily GOV.UK figure checker detected a routine figure change that cleared the guarded auto-merge checks — every value is plausible, in range, and a small move. **This PR merges automatically once CI passes.**",
      "",
      "### Figures changed",
      changes,
      "",
      SOURCE_LINKS,
      "",
      "> Auto-generated by the GOV.UK figure freshness checker. A passing build does not verify the figures are correct. If auto-merge is not enabled, cross-check the values above against the sources before merging manually; if anything looks wrong, close the PR and check the scraper. This description is regenerated on each update — add review notes as comments, not here.",
      "",
    ].join("\n");
  }

  const reasons = (reviewReasons ?? ["(see the check report artifact)"])
    .map((r) => `- ${r}`)
    .join("\n");
  return [
    "## Summary",
    "",
    "The daily GOV.UK figure checker detected a change that needs a human before it ships (a structural field, an out-of-range value, a large jump, a decrease, or content drift).",
    "",
    "### Flagged for review",
    reasons,
    "",
    "### Figures changed",
    changes,
    "",
    "## Review checklist",
    "- [ ] Verify the changed values against GOV.UK",
    "- [ ] Check the CURRENT_RATES period comments in src/lib/loans/plans.ts",
    "- [ ] Verify the figures in public/llms.txt",
    "",
    SOURCE_LINKS,
    "",
    "> Auto-generated by the GOV.UK figure freshness checker. This description is regenerated on each update — add review notes as comments, not here.",
    "",
  ].join("\n");
}
